name: AutoCorrect Lint

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: AutoCorrect
        uses: huacnlee/autocorrect-action@v1.5.5
